name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Debug Secrets
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "USERNAME=$USERNAME"
          echo "HOST=$HOST"

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $USERNAME@$HOST '
            set -e
            cd /home/ubuntu/Eat-with-me-POS
            # Discard any local changes (BEFORE pulling new code)
            git reset --hard
            git clean -fd
            git pull origin main
            rm -rf node_modules dist
            npm install
            npm install @prisma/client
            npx prisma generate --schema=prisma/master/master.prisma
            npx prisma generate --schema=prisma/tenant/schema.prisma
            npx tsc
            # --- Copy generated Prisma master client to dist directory ---
            mkdir -p dist/generated
            cp -r src/generated/master dist/generated/
            # Make script executable and run it
            chmod +x scripts/load-env-and-start.sh
            ./scripts/load-env-and-start.sh          '
